export const SEARCH_VERSES = 'SEARCH_VERSES';
export const CLEAR_VERSES = 'CLEAR_VERSES';
export const SET_LOADING = 'SET_LOADING';
export const GET_VERSE_ASSOCIATIONS = 'GET_VERSE_ASSOCIATIONS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';




